#!/bin/bash
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
echo   Deploy App Service for Web Application
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
echo ---Environment Variables
echo "B2C_INSTANCE: $B2C_INSTANCE"
echo "B2C_WEB_CLIENTID: $B2C_WEB_CLIENTID"
echo "B2C_API_CLIENTID: $B2C_API_CLIENTID"
echo "B2C_WEB_CLIENTSECRET: B2C_WEB_CLIENTSECRET"
echo "B2C_DOMAIN: $B2C_DOMAIN"
echo "B2C_SIGNEDOUT_CALLBACK_PATH: $B2C_SIGNEDOUT_CALLBACK_PATH"
echo "B2C_SIGNUPSIGNIN_POLICYID: $B2C_SIGNUPSIGNIN_POLICYID"
echo "B2C_RESETPASSWORD_POLICYID: B2C_RESETPASSWORD_POLICYID"
echo "B2C_EDITPROFILE_POLICYID: $B2C_EDITPROFILE_POLICYID"
echo "B2C_CALLBACK_PATH: $B2C_EDITPROFILE_POLICYID"
echo "TODO_SCOPE: $TODO_SCOPE"
echo "TODO_BASEADDRESS: $TODO_BASEADDRESS"
echo "TODO_BASEADDRESS: $TODO_BASEADDRESS"
