# This workflow will deploy the front end component of the application.
# To get this workflow to trigger you need to edit one of the files in the Sirmione-Web project.
# to change the name of the resource edit the ALIAS below

on:
  push:
    paths:
    - Client/**

name: Deploy_Web_Site
env:
   APPLICATION_NAME_ROOT: llicla

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Setup .NET Core 3.1.101
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101  
        
    - name: Build Application
      run: dotnet build Client/TodoListClient.csproj --configuration Debug

    - name: Publish Application
      run: |
        dotnet publish Client/TodoListClient.csproj -c Debug -o ${{env.DOTNET_ROOT}}/myapp 
        
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
   
    - name: 'Deploy CLA Web Application'
      uses: azure/webapps-deploy@v1
      with: 
        app-name: ${{env.APPLICATION_NAME_ROOT}}-web
        package: ${{env.DOTNET_ROOT}}/myapp 
       
    
